services:
  upsignon-pro-db:
    image: postgres
    restart: always
    env_file:
      - db-pwd.env
    environment:
      POSTGRES_USER: upsignonpro
      POSTGRES_DB: upsignonpro
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - upsignon-pro-db:/var/lib/postgresql/data

  upsignon-pro-server:
    image: giregdekerdanet/upsignon-pro-server
    restart: always
    depends_on:
      - upsignon-pro-db
    ports:
      - 3000:3000
    env_file:
      - db-pwd.env
      - server.env
    init: true
    environment:
      DB_USER: upsignonpro
      DB_NAME: upsignonpro
      DB_HOST: upsignon-pro-db
      DB_PORT: 5432

  upsignon-pro-dashboard:
    image: giregdekerdanet/upsignon-pro-dashboard
    restart: always
    depends_on:
      - upsignon-pro-db
    ports:
      - 3001:3001
    env_file:
      - db-pwd.env
      - dashboard.env
    init: true
    environment:
      DB_USER: upsignonpro
      DB_NAME: upsignonpro
      DB_HOST: upsignon-pro-db
      DB_PORT: 5432

  upsignon-pro-nginx:
    image: giregdekerdanet/upsignon-nginx-all-in-one
    restart: always
    depends_on:
      - upsignon-pro-server
      - upsignon-pro-dashboard
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certificate:/etc/nginx/ssl/:ro

volumes:
  upsignon-pro-db:
