import fs from 'fs';

const {
  DB_USER,
  DB_PASS,
  DB_NAME,
  DB_HOST,
  DB_PORT,
  POSTGRES_PASSWORD,
  DB_BACKUP_DIR,
  NODE_ENV,
  API_PUBLIC_HOSTNAME,
  SESSION_SECRET,
  SERVER_PORT,
  SSL_CERTIFICATE_KEY_PATH, // DEPRECATED
  SSL_CERTIFICATE_CRT_PATH, // DEPRECATED
  LOCALHOST_SSL_CERTIFICATE_KEY_PATH,
  LOCALHOST_SSL_CERTIFICATE_CRT_PATH,
  HTTP_PROXY,
  USE_POSTFIX,
  DKIM_HOSTNAME, // DEPRECATED
  SENDING_MAIL,
  DKIM_KEY_SELECTOR,
  DKIM_PRIVATE_KEY_PATH,
  STATUS_SERVER_URL, // DEV ONLY
} = process.env;

const USE_POSTFIX_BOOL = USE_POSTFIX === 'true';
let DKIM_PRIVATE_KEY;
if (!!USE_POSTFIX_BOOL && !!DKIM_PRIVATE_KEY_PATH) {
  DKIM_PRIVATE_KEY = fs.readFileSync(DKIM_PRIVATE_KEY_PATH);
}

export default {
  IS_PRODUCTION: NODE_ENV !== 'development',
  DB_HOST,
  DB_PORT: DB_PORT ? Number.parseInt(DB_PORT) : 5432,
  DB_USER,
  DB_NAME,
  DB_PASS: POSTGRES_PASSWORD || DB_PASS,
  DB_BACKUP_DIR: DB_BACKUP_DIR,
  SERVER_PORT: SERVER_PORT ? Number.parseInt(SERVER_PORT) : 3000,
  API_PUBLIC_HOSTNAME: API_PUBLIC_HOSTNAME?.replace(/\/$/, '') || '',
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  SESSION_SECRET: SESSION_SECRET || require('crypto').randomBytes(64).toString('hex'),
  LOCALHOST_SSL_CERTIFICATE_KEY_PATH:
    LOCALHOST_SSL_CERTIFICATE_KEY_PATH || SSL_CERTIFICATE_KEY_PATH || '',
  LOCALHOST_SSL_CERTIFICATE_CRT_PATH:
    LOCALHOST_SSL_CERTIFICATE_CRT_PATH || SSL_CERTIFICATE_CRT_PATH || '',
  HTTP_PROXY,
  USE_POSTFIX: USE_POSTFIX_BOOL,
  SENDING_MAIL: SENDING_MAIL || `ne-pas-repondre@${DKIM_HOSTNAME}`,
  DKIM_KEY_SELECTOR,
  DKIM_PRIVATE_KEY,
  STATUS_SERVER_URL: (STATUS_SERVER_URL || 'https://app.upsignon.eu').replace(/\/$/, ''),
};
